### ISSUE TITLE
ValueError when trying to open BAI index directly using parse_index()

### ISSUE THREAD

**Issue by Damien-Black** [jdidion/ngsindex#1]
**Motivation**

Attempting to load *.bai to programmatically calculate coverage in BAM

**Issue**

Encountered the following `ValueError`

```python
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/dnanexus/miniconda2/envs/py36/lib/python3.6/site-packages/ngsindex/__init__.py", line 775, in parse_index
        with BinReader(path=path, byte_order="<", **kwargs) as reader:
      File "/home/dnanexus/miniconda2/envs/py36/lib/python3.6/site-packages/ngsindex/utils.py", line 111, in __enter__
        self.open()
      File "/home/dnanexus/miniconda2/envs/py36/lib/python3.6/site-packages/ngsindex/utils.py", line 122, in open
        self._reader = xopen(self.path, "rb", context_wrapper=True)
      File "/home/dnanexus/miniconda2/envs/py36/lib/python3.6/site-packages/xphyle/__init__.py", line 1021, in xopen
        raise ValueError("Cannot determine file mode")
    ValueError: Cannot determine file mode
```

**Initial Investigation**

While checking to see if I was consuming `ngsindex.parse_index` incorrectly I noticed the `BinReader` [context call](https://github.com/jdidion/ngsindex/blob/60a4e7985b6504e36481b7ba137dc48f8d0e696c/ngsindex/__init__.py#L775), which is resolved by calling the `open` method on BinReader then to `xopen`. The specific [xopen call](https://github.com/jdidion/ngsindex/blob/master/ngsindex/utils.py#L122):
```python
def open(self) -> None:
    """Opens the reader."""
    self._reader = xopen(self.path, "rb", context_wrapper=True)
```

This call sends over a Concrete Path to the `xopen` method.  When the file_type is parsed in `xopen`:
1. From [the comments](https://github.com/jdidion/xphyle/blob/227d52f5ea994edb1c9000687e9148f6f56da73a/xphyle/__init__.py#L815-L823) in `xopen` method it seems a `PosixPath` should be resolved as a `FileType.LOCAL`
2. From the [following checks](https://github.com/jdidion/xphyle/blob/227d52f5ea994edb1c9000687e9148f6f56da73a/xphyle/__init__.py#L860-L884), specifically the [not str check](https://github.com/jdidion/xphyle/blob/227d52f5ea994edb1c9000687e9148f6f56da73a/xphyle/__init__.py#L865), it looks like `file_type` is incorrectly set to `FileType.FILELIKE`.

I think thats what leads to the issue I encountered, but unsure whether it's better to resolve in the consumer `ngsindex` or in `xphyle`.

**Comment by jdidion** [comment]
Hi Steve, I think is a version issue. xphyle 4+ is required for this to work correctly. xphyle4 is currently pre-release, and I had setup.py configured incorrectly so that it would ignore prereleases. I've fixed this in master. Can you try again?
